# Generated by Django 5.0.6 on 2024-06-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
    ]
