# Generated by Django 5.0.6 on 2024-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
