# Generated by Django 5.0.6 on 2024-06-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_municipio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Register',
        ),
    ]
