# Generated by Django 5.0.6 on 2024-07-01 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
