# Generated by Django 5.0.6 on 2024-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0002_plano_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
