# Generated by Django 5.0.6 on 2024-07-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0003_alter_plano_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='outro_campo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
