# Generated by Django 5.0.6 on 2024-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0004_plano_outro_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='inicio_prazo',
            field=models.DateField(default=None),
        ),
    ]
