# Generated by Django 5.0.6 on 2024-07-01 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0005_alter_plano_inicio_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='inicio_prazo',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
    ]
