# Generated by Django 5.0.6 on 2024-07-01 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0006_alter_plano_inicio_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='inicio_prazo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
