# Generated by Django 5.0.6 on 2024-07-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0007_alter_plano_inicio_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='outro_campo',
        ),
    ]
