# Generated by Django 5.0.6 on 2024-06-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('inicio_prazo', models.DateField()),
                ('final_prazo', models.DateField()),
                ('categoria', models.CharField(choices=[('rio', 'Rio'), ('infraestrutura', 'Infraestrutura'), ('meio_ambiente', 'Meio Ambiente'), ('hidro', 'Hidro')], max_length=50)),
                ('introducao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='topicos/')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='plano.plano')),
            ],
        ),
    ]
