# Generated by Django 5.0.6 on 2024-06-19 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('inicio_prazo', models.DateField()),
                ('final_prazo', models.DateField()),
                ('categoria', models.CharField(choices=[('rio', 'Rio'), ('infraestrutura', 'Infraestrutura'), ('meio_ambiente', 'Meio Ambiente'), ('hidro', 'Hidro')], max_length=50)),
                ('introducao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_biblioteca', models.FileField(upload_to='biblioteca/')),
                ('imagem_biblioteca', models.ImageField(upload_to='biblioteca/')),
                ('url_biblioteca', models.URLField()),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo_adicional', models.CharField(max_length=100)),
                ('texto_adicional', models.TextField()),
                ('arquivo_pdf_adicional', models.FileField(blank=True, null=True, upload_to='topicos/', verbose_name='Arquivo PDF Adicional')),
                ('imagem_adicional', models.ImageField(blank=True, null=True, upload_to='topicos/', verbose_name='Imagem Adicional')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_acao', models.CharField(choices=[('acao', 'Ação'), ('meta', 'Meta'), ('diretriz', 'Diretriz'), ('objetivo', 'Objetivo'), ('recomendacao', 'Recomendação')], max_length=50)),
                ('titulo_acao', models.CharField(max_length=100)),
                ('descricao_acao', models.TextField()),
                ('inicio_prazo_acao', models.DateField()),
                ('final_prazo_acao', models.DateField()),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='topicos/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='topicos/', verbose_name='Arquivo PDF')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
            ],
        ),
    ]
