# Generated by Django 5.0.6 on 2024-06-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano'),
        ),
    ]
